// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAju2V_2tBKgbCz3R4f7JTqNukWeuLhAH4',
    appId: '1:564635862020:web:b4e4479090865f5e88e151',
    messagingSenderId: '564635862020',
    projectId: 'fir-test-a9233',
    authDomain: 'fir-test-a9233.firebaseapp.com',
    storageBucket: 'fir-test-a9233.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcyind6anwsNN8t4Q1rLUnT9JfXxKVp_0',
    appId: '1:564635862020:android:1597a127b140381b88e151',
    messagingSenderId: '564635862020',
    projectId: 'fir-test-a9233',
    storageBucket: 'fir-test-a9233.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzLHvbnKKkwt4Oiqnqpn29o0PdYAYi_4s',
    appId: '1:564635862020:ios:203589855db3404488e151',
    messagingSenderId: '564635862020',
    projectId: 'fir-test-a9233',
    storageBucket: 'fir-test-a9233.appspot.com',
    iosClientId: '564635862020-ec45fr060n5cl18htt31cm6bchs1u0oh.apps.googleusercontent.com',
    iosBundleId: 'com.example.fTest',
  );
}
